
# site settings
locale: "ko-KR"
title: Akashic Record
email: codeguru.sivese@gmail.com
description: >- 
  Think & Write, repeat
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sivese.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

#twitter_username: jekyllrb
github_username:  sivese

plugins:

